import { ArabicLetter } from './types';

// We use Tatweel (ـ) to show connection points visually in the UI if needed, 
// but modern browsers shape Arabic correctly automatically. 
// However, to force the display of specific forms in isolation, we often use the Tatweel.

export const ARABIC_LETTERS: ArabicLetter[] = [
  {
    id: 1,
    name: "Alif",
    transliteration: "aa",
    zhuyin: "ㄚ",
    isolated: "ا",
    initial: "ا",
    medial: "ـا",
    final: "ـا",
    description: "像一根直直的棍子，發長音的「啊」。",
    exampleWord: { arabic: "أَرْنَب", transliteration: "arnab", meaning: "兔子" }
  },
  {
    id: 2,
    name: "Ba",
    transliteration: "b",
    zhuyin: "ㄅ",
    isolated: "ب",
    initial: "بـ",
    medial: "ـبـ",
    final: "ـب",
    description: "下面有一個點點，像個微笑的盤子。",
    exampleWord: { arabic: "بَطَّة", transliteration: "baTTa", meaning: "鴨子" }
  },
  {
    id: 3,
    name: "Ta",
    transliteration: "t",
    zhuyin: "ㄊ",
    isolated: "ت",
    initial: "تـ",
    medial: "ـتـ",
    final: "ـت",
    description: "上面有兩個點點，像兩顆眼睛。",
    exampleWord: { arabic: "تُفَّاح", transliteration: "tuffaaH", meaning: "蘋果" }
  },
  {
    id: 4,
    name: "Tha",
    transliteration: "th",
    zhuyin: "ㄙ (咬舌)",
    isolated: "ث",
    initial: "ثـ",
    medial: "ـثـ",
    final: "ـث",
    description: "上面有三個點點，記得要輕輕咬舌頭喔！",
    exampleWord: { arabic: "ثَعْلَب", transliteration: "tha'lab", meaning: "狐狸" }
  },
  {
    id: 5,
    name: "Jim",
    transliteration: "j",
    zhuyin: "ㄐ",
    isolated: "ج",
    initial: "جـ",
    medial: "ـجـ",
    final: "ـج",
    description: "肚子裡有一個點點。",
    exampleWord: { arabic: "جَمَل", transliteration: "jamal", meaning: "駱駝" }
  },
  {
    id: 6,
    name: "Ha",
    transliteration: "H",
    zhuyin: "ㄏ (深喉)",
    isolated: "ح",
    initial: "حـ",
    medial: "ـحـ",
    final: "ـح",
    description: "沒有點點，聲音從喉嚨深處發出來，像呵氣。",
    exampleWord: { arabic: "حِصَان", transliteration: "HiSaan", meaning: "馬" }
  },
  {
    id: 7,
    name: "Kha",
    transliteration: "kh",
    zhuyin: "ㄎ (喉音)",
    isolated: "خ",
    initial: "خـ",
    medial: "ـخـ",
    final: "ـخ",
    description: "點點在頭頂上，像喉嚨癢癢的聲音。",
    exampleWord: { arabic: "خُبْز", transliteration: "khubz", meaning: "麵包" }
  },
  {
    id: 8,
    name: "Dal",
    transliteration: "d",
    zhuyin: "ㄉ",
    isolated: "د",
    initial: "د",
    medial: "ـد",
    final: "ـد",
    description: "彎彎的，像個開口。",
    exampleWord: { arabic: "دِيك", transliteration: "diik", meaning: "公雞" }
  },
  {
    id: 9,
    name: "Dhal",
    transliteration: "dh",
    zhuyin: "ㄗ (咬舌)",
    isolated: "ذ",
    initial: "ذ",
    medial: "ـذ",
    final: "ـذ",
    description: "彎彎的頭上有一個點點，要咬舌頭喔。",
    exampleWord: { arabic: "ذُرَة", transliteration: "dhura", meaning: "玉米" }
  },
  {
    id: 10,
    name: "Ra",
    transliteration: "r",
    zhuyin: "ㄌ (彈舌)",
    isolated: "ر",
    initial: "ر",
    medial: "ـر",
    final: "ـر",
    description: "像溜滑梯一樣溜下來。",
    exampleWord: { arabic: "رَجُل", transliteration: "rajul", meaning: "男人" }
  },
  {
    id: 11,
    name: "Zay",
    transliteration: "z",
    zhuyin: "ㄗ (震動)",
    isolated: "ز",
    initial: "ز",
    medial: "ـز",
    final: "ـز",
    description: "溜滑梯上面有一個點點，像蜜蜂嗡嗡叫。",
    exampleWord: { arabic: "زَهْرَة", transliteration: "zahra", meaning: "花" }
  },
  {
    id: 12,
    name: "Sin",
    transliteration: "s",
    zhuyin: "ㄙ",
    isolated: "س",
    initial: "سـ",
    medial: "ـسـ",
    final: "ـس",
    description: "有三個牙齒，像鋸子一樣。",
    exampleWord: { arabic: "سَمَكَة", transliteration: "samaka", meaning: "魚" }
  },
  {
    id: 13,
    name: "Shin",
    transliteration: "sh",
    zhuyin: "ㄕ",
    isolated: "ش",
    initial: "شـ",
    medial: "ـشـ",
    final: "ـش",
    description: "三個牙齒上面有三個點點。",
    exampleWord: { arabic: "شَمْس", transliteration: "shams", meaning: "太陽" }
  },
  {
    id: 14,
    name: "Sad",
    transliteration: "S",
    zhuyin: "ㄙ (重音)",
    isolated: "ص",
    initial: "صـ",
    medial: "ـصـ",
    final: "ـص",
    description: "吹氣球的形狀，嘴巴要鼓起來發音。",
    exampleWord: { arabic: "صَقْر", transliteration: "Saqr", meaning: "老鷹" }
  },
  {
    id: 15,
    name: "Dad",
    transliteration: "D",
    zhuyin: "ㄉ (重音)",
    isolated: "ض",
    initial: "ضـ",
    medial: "ـضـ",
    final: "ـض",
    description: "吹氣球上面有一個點點，這是阿拉伯語特有的聲音喔！",
    exampleWord: { arabic: "ضِفْدَع", transliteration: "Difda'", meaning: "青蛙" }
  },
  {
    id: 16,
    name: "Ta (Emphatic)",
    transliteration: "T",
    zhuyin: "ㄊ (重音)",
    isolated: "ط",
    initial: "طـ",
    medial: "ـطـ",
    final: "ـط",
    description: "形狀像個小旗子，聲音要渾厚。",
    exampleWord: { arabic: "طَائِرَة", transliteration: "Taa'ira", meaning: "飛機" }
  },
  {
    id: 17,
    name: "Zha",
    transliteration: "Z",
    zhuyin: "ㄗ (重咬舌)",
    isolated: "ظ",
    initial: "ظـ",
    medial: "ـظـ",
    final: "ـظ",
    description: "小旗子上面有一個點點，要咬著舌頭發重音。",
    exampleWord: { arabic: "ظَرْف", transliteration: "Zarf", meaning: "信封" }
  },
  {
    id: 18,
    name: "Ayn",
    transliteration: "'",
    zhuyin: "喉壁音",
    isolated: "ع",
    initial: "عـ",
    medial: "ـعـ",
    final: "ـع",
    description: "嘴巴張開，像是在檢查喉嚨。",
    exampleWord: { arabic: "عَيْن", transliteration: "'ayn", meaning: "眼睛" }
  },
  {
    id: 19,
    name: "Ghayn",
    transliteration: "gh",
    zhuyin: "ㄍ (漱口音)",
    isolated: "غ",
    initial: "غـ",
    medial: "ـغـ",
    final: "ـغ",
    description: "頭上有個點點，像漱口的聲音。",
    exampleWord: { arabic: "غَزَال", transliteration: "ghazaal", meaning: "羚羊" }
  },
  {
    id: 20,
    name: "Fa",
    transliteration: "f",
    zhuyin: "ㄈ",
    isolated: "ف",
    initial: "فـ",
    medial: "ـفـ",
    final: "ـف",
    description: "頭上有一個點點的圈圈。",
    exampleWord: { arabic: "فِيل", transliteration: "fiil", meaning: "大象" }
  },
  {
    id: 21,
    name: "Qaf",
    transliteration: "q",
    zhuyin: "ㄍ (喉深)",
    isolated: "ق",
    initial: "قـ",
    medial: "ـقـ",
    final: "ـق",
    description: "頭上有兩個點點，聲音很深。",
    exampleWord: { arabic: "قَلَم", transliteration: "qalam", meaning: "筆" }
  },
  {
    id: 22,
    name: "Kaf",
    transliteration: "k",
    zhuyin: "ㄎ",
    isolated: "ك",
    initial: "كـ",
    medial: "ـكـ",
    final: "ـك",
    description: "形狀像個開口笑，輕快的聲音。",
    exampleWord: { arabic: "كَلْب", transliteration: "kalb", meaning: "狗" }
  },
  {
    id: 23,
    name: "Lam",
    transliteration: "l",
    zhuyin: "ㄌ",
    isolated: "ل",
    initial: "لـ",
    medial: "ـلـ",
    final: "ـل",
    description: "像一支雨傘柄。",
    exampleWord: { arabic: "لَيْمُون", transliteration: "laymuun", meaning: "檸檬" }
  },
  {
    id: 24,
    name: "Mim",
    transliteration: "m",
    zhuyin: "ㄇ",
    isolated: "م",
    initial: "مـ",
    medial: "ـمـ",
    final: "ـم",
    description: "像個小蝌蚪。",
    exampleWord: { arabic: "مَوْز", transliteration: "mawz", meaning: "香蕉" }
  },
  {
    id: 25,
    name: "Nun",
    transliteration: "n",
    zhuyin: "ㄋ",
    isolated: "ن",
    initial: "نـ",
    medial: "ـنـ",
    final: "ـن",
    description: "像個碗，裡面有一顆丸子。",
    exampleWord: { arabic: "نَجْمَة", transliteration: "najma", meaning: "星星" }
  },
  {
    id: 26,
    name: "Ha",
    transliteration: "h",
    zhuyin: "ㄏ",
    isolated: "ه",
    initial: "هـ",
    medial: "ـهـ",
    final: "ـه",
    description: "像個蝴蝶結，輕輕的呼吸聲。",
    exampleWord: { arabic: "هَرَم", transliteration: "haram", meaning: "金字塔" }
  },
  {
    id: 27,
    name: "Waw",
    transliteration: "w / uu",
    zhuyin: "ㄨ",
    isolated: "و",
    initial: "و",
    medial: "ـو",
    final: "ـو",
    description: "像個逗號，嘴巴嘟圓圓。",
    exampleWord: { arabic: "وَرْدَة", transliteration: "warda", meaning: "玫瑰" }
  },
  {
    id: 28,
    name: "Ya",
    transliteration: "y / ii",
    zhuyin: "ㄧ",
    isolated: "ي",
    initial: "يـ",
    medial: "ـيـ",
    final: "ـي",
    description: "下面有兩顆點點，像鴨子在水裡。",
    exampleWord: { arabic: "يَد", transliteration: "yad", meaning: "手" }
  }
];